x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA='
    AIRFLOW__WEBSERVER__SECRET_KEY: 'change_me_secret_key'
    AIRFLOW_UID: '50000'
    DBT_PROJECT_DIR: /opt/airflow/project
    DBT_PROFILES_DIR: /opt/airflow/project/docker
  volumes:
    - ./dags:/opt/airflow/dags
    - ./:/opt/airflow/project
    - ./data:/opt/airflow/data
  depends_on:
    airflow-db:
      condition: service_healthy

services:
  airflow-db:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U airflow -d airflow']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'

  airflow-init:
    <<: *airflow-common
    command: bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - '8080:8080'

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
